name: daily-run

on:
  schedule:
    - cron: "0 21 * * *"   # JST 06:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run orchestrator
        env:                           # ← これが重要
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID_CONTENT: ${{ secrets.NOTION_DB_ID_CONTENT }}
        run: |
          python orchestrator/run.py
