name: daily-run
on:
  schedule:
    - cron: "0 21 * * *"   # JST 06:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (ffmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run orchestrator
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID_CONTENT: ${{ secrets.NOTION_DB_ID_CONTENT }}
          # Instagram / YouTube は今はドライラン。実線時にSecretsを追加
          IG_ACCESS_TOKEN_LONG_LIVED: ${{ secrets.IG_ACCESS_TOKEN_LONG_LIVED }}
          IG_BUSINESS_ACCOUNT_ID: ${{ secrets.IG_BUSINESS_ACCOUNT_ID }}
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          PUBLISH_DRY_RUN: "true"
        run: |
          python orchestrator/run.py
